mappings:
  axes:
    - axes[1]
    - axes[0] * -1.0
    - axes[4]
    - axes[3]
    - axes[2]
    - axes[5]

    
  buttons:
    - buttons[0]
    - buttons[1]
    - buttons[2]
    - buttons[3]
    - buttons[4]
    - buttons[5]
    - buttons[6]
    - buttons[7]
    - buttons[8]
    - buttons[9]
    - buttons[10]
    - max(axes[6],0.0)
    - min(axes[6],0.0) * -1.0
    - min(axes[7],0.0) * -1.0
    - max(axes[7],0.0)
