mappings:
    arm: 0
    disarm: 1
    depth_hold: 3
    manual: 2
    stabilize: 4
    light_inc: -1
    light_dec: -1
    gain_inc: -1
    gain_dec: -1
    mount_center: -1
    mount_inc: -1
    mount_dec: -1
    shift: -1
    input_hold: -1

# arm: 512 (9)
# disarm: 256 (8)
# gain_inc 14
# gain_dec 15
# manual 2
# alt_hold 0
# stabilize 3
