auto_yaw: false
read_wrench: 0
compensate_d: true
starting_setpt: [10.0, 10.0, -20.0]

ctrller_type: 2 # mpc = 0; dompc = 1; pid = 2

Kp_list: [2000.0, 2000.0, 2000.0, 0.2]
Ki_list: [0.0, 0.0, 0.0, 0.0]
Kd_list: [0.0, 0.0, 0.0, 0.0]

