auto_yaw: false
ref_traj: /home/fyp/bluerov_ws/src/bluerov2/bluerov2_mpc/traj/circle.txt
yaml_name: /config/gazebo_param.yaml
disturbance_x: 0.0
disturbance_y: 0.0
disturbance_z: 0.0
disturbance_phi: 0.0
disturbance_theta: 0.0
disturbance_psi: 0.0