auto_yaw: false
read_wrench: 0
compensate_d: false
# ref_traj: /root/uuv_ws/src/dave_sim/bluerov2/bluerov2_mpc/traj/slam_pool.txt
ref_traj: /root/uuv_ws/src/dave_sim/bluerov2/bluerov2_mpc/traj/slam_pool_side.txt
applied_forcex: /root/uuv_ws/src/dave_sim/bluerov2/bluerov2_dobmpc/config/forcex.txt
applied_forcey: /root/uuv_ws/src/dave_sim/bluerov2/bluerov2_dobmpc/config/forcey.txt
applied_forcez: /root/uuv_ws/src/dave_sim/bluerov2/bluerov2_dobmpc/config/forcez.txt
applied_torquez: /root/uuv_ws/src/dave_sim/bluerov2/bluerov2_dobmpc/config/torquez.txt
yaml_name: /config/gazebo_param_copy.yaml