  -
    component: velocity
    mean: 0.3
    min: 0.0
    max: 0.6
    noise: 0.1
    mu: 0.0
  -
    component: horz_angle
    mean: 15
    min: 0.0
    max: 30
    noise: 1
    mu: 0.0
  -
    component: vert_angle
    mean: 15
    min: 0.0
    max: 30
    noise: 1
    mu: 0.0
