accel_r_kd: 0.0
accel_r_ki: 0.0
accel_r_kp: 1.0
accel_r_sat: 1.0
accel_x_kd: 0.0
accel_x_ki: 0.0
accel_x_kp: 1.0
accel_x_sat: 1.0
accel_y_kd: 0.0
accel_y_ki: 0.0
accel_y_kp: 1.0
accel_y_sat: 1.0
accel_z_kd: 0.0
accel_z_ki: 0.0
accel_z_kp: 1.0
accel_z_sat: 1.0
pid:
  inertial: {ixx: 5.0, ixy: 0, ixz: 0, iyy: 10.0, iyz: 0, izz: 10.0}
  mass: 15.0
pos_r_kd: 0.0
pos_r_ki: 0.0
pos_r_kp: 1.0
pos_r_sat: 0.5
pos_x_kd: 0.0
pos_x_ki: 0.0
pos_x_kp: 1.0
pos_x_sat: 1.0
pos_y_kd: 0.0
pos_y_ki: 0.0
pos_y_kp: 1.0
pos_y_sat: 1.0
pos_z_kd: 0.0
pos_z_ki: 0.0
pos_z_kp: 1.0
pos_z_sat: 1.0
use_accel_fb: false
vel_r_kd: 0.01
vel_r_ki: 2.0
vel_r_kp: 1.0
vel_r_lim: 0.5
vel_r_sat: 10.0
vel_x_kd: 0.01
vel_x_ki: 2.0
vel_x_kp: 1.0
vel_x_lim: 1.0
vel_x_sat: 10
vel_y_kd: 0.01
vel_y_ki: 2.0
vel_y_kp: 1.0
vel_y_lim: 1.0
vel_y_sat: 10
vel_z_kd: 0.01
vel_z_ki: 2.0
vel_z_kp: 1.0
vel_z_lim: 1.0
vel_z_sat: 10
