/* This file was automatically generated by CasADi 3.6.4.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) bluerov2_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[3] = {0, 0, 0};

/* bluerov2_expl_ode_fun:(i0[12],i1[4],i2[])->(o0[12]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][5] : 0;
  a1=cos(a0);
  a2=arg[0]? arg[0][4] : 0;
  a3=cos(a2);
  a1=(a1*a3);
  a3=arg[0]? arg[0][6] : 0;
  a1=(a1*a3);
  a4=cos(a0);
  a5=sin(a2);
  a4=(a4*a5);
  a5=arg[0]? arg[0][3] : 0;
  a6=sin(a5);
  a4=(a4*a6);
  a6=sin(a0);
  a7=cos(a5);
  a6=(a6*a7);
  a4=(a4-a6);
  a6=arg[0]? arg[0][7] : 0;
  a4=(a4*a6);
  a1=(a1+a4);
  a4=sin(a0);
  a7=sin(a5);
  a4=(a4*a7);
  a7=cos(a0);
  a8=cos(a5);
  a7=(a7*a8);
  a8=sin(a2);
  a7=(a7*a8);
  a4=(a4+a7);
  a7=arg[0]? arg[0][8] : 0;
  a4=(a4*a7);
  a1=(a1+a4);
  if (res[0]!=0) res[0][0]=a1;
  a1=sin(a0);
  a4=cos(a2);
  a1=(a1*a4);
  a1=(a1*a3);
  a4=cos(a0);
  a8=cos(a5);
  a4=(a4*a8);
  a8=sin(a5);
  a9=sin(a2);
  a8=(a8*a9);
  a9=sin(a0);
  a8=(a8*a9);
  a4=(a4+a8);
  a4=(a4*a6);
  a1=(a1+a4);
  a4=sin(a2);
  a8=sin(a0);
  a4=(a4*a8);
  a8=cos(a5);
  a4=(a4*a8);
  a8=cos(a0);
  a9=sin(a5);
  a8=(a8*a9);
  a4=(a4-a8);
  a4=(a4*a7);
  a1=(a1+a4);
  if (res[0]!=0) res[0][1]=a1;
  a1=cos(a2);
  a4=sin(a5);
  a1=(a1*a4);
  a1=(a1*a6);
  a4=sin(a2);
  a4=(a4*a3);
  a1=(a1-a4);
  a4=cos(a2);
  a8=cos(a5);
  a4=(a4*a8);
  a4=(a4*a7);
  a1=(a1+a4);
  if (res[0]!=0) res[0][2]=a1;
  a1=arg[0]? arg[0][9] : 0;
  a0=sin(a0);
  a4=sin(a2);
  a0=(a0*a4);
  a4=cos(a2);
  a0=(a0/a4);
  a4=arg[0]? arg[0][10] : 0;
  a0=(a0*a4);
  a0=(a1+a0);
  a8=cos(a5);
  a9=sin(a2);
  a8=(a8*a9);
  a9=cos(a2);
  a8=(a8/a9);
  a9=arg[0]? arg[0][11] : 0;
  a8=(a8*a9);
  a0=(a0+a8);
  if (res[0]!=0) res[0][3]=a0;
  a0=cos(a5);
  a0=(a0*a4);
  a8=sin(a5);
  a8=(a8*a9);
  a0=(a0+a8);
  if (res[0]!=0) res[0][4]=a0;
  a0=sin(a5);
  a8=cos(a2);
  a0=(a0/a8);
  a0=(a0*a4);
  a8=cos(a5);
  a10=cos(a2);
  a8=(a8/a10);
  a8=(a8*a9);
  a0=(a0+a8);
  if (res[0]!=0) res[0][5]=a0;
  a0=7.7052287682421297e-02;
  a8=7.0699999999999996e-01;
  a10=arg[1]? arg[1][1] : 0;
  a11=arg[1]? arg[1][0] : 0;
  a12=(a10-a11);
  a13=arg[1]? arg[1][3] : 0;
  a12=(a12+a13);
  a14=(a8*a12);
  a15=(a11+a10);
  a15=(a15+a13);
  a16=(a8*a15);
  a14=(a14-a16);
  a16=-7.0699999999999996e-01;
  a17=(a11+a10);
  a17=(a17-a13);
  a18=(a16*a17);
  a14=(a14+a18);
  a11=(a11-a10);
  a11=(a11+a13);
  a13=(a16*a11);
  a14=(a14+a13);
  a13=1.1260000000000000e+01;
  a10=(a13*a9);
  a10=(a10*a6);
  a14=(a14+a10);
  a10=(a13*a4);
  a10=(a10*a7);
  a14=(a14-a10);
  a10=1.9620000000000002e+00;
  a18=sin(a2);
  a18=(a10*a18);
  a14=(a14-a18);
  a0=(a0*a14);
  if (res[0]!=0) res[0][6]=a0;
  a0=8.8809946714031973e-02;
  a14=(a8*a12);
  a18=(a16*a15);
  a14=(a14-a18);
  a8=(a8*a17);
  a14=(a14+a8);
  a16=(a16*a11);
  a14=(a14+a16);
  a16=(a13*a9);
  a16=(a16*a3);
  a14=(a14-a16);
  a16=(a13*a1);
  a16=(a16*a7);
  a14=(a14+a16);
  a16=cos(a2);
  a16=(a10*a16);
  a7=sin(a5);
  a16=(a16*a7);
  a14=(a14+a16);
  a0=(a0*a14);
  if (res[0]!=0) res[0][7]=a0;
  a0=5.9780009564801527e-02;
  a14=(a13*a4);
  a14=(a14*a3);
  a3=arg[1]? arg[1][2] : 0;
  a3=(a3+a3);
  a14=(a14-a3);
  a13=(a13*a1);
  a13=(a13*a6);
  a14=(a14-a13);
  a13=cos(a2);
  a10=(a10*a13);
  a13=cos(a5);
  a10=(a10*a13);
  a14=(a14+a10);
  a0=(a0*a14);
  if (res[0]!=0) res[0][8]=a0;
  a0=3.3333333333333335e+00;
  a14=5.0000000000000044e-02;
  a14=(a14*a4);
  a14=(a14*a9);
  a10=2.2092120000000004e+00;
  a13=cos(a2);
  a13=(a10*a13);
  a5=sin(a5);
  a13=(a13*a5);
  a14=(a14-a13);
  a0=(a0*a14);
  if (res[0]!=0) res[0][9]=a0;
  a0=5.3245301102177733e-01;
  a14=2.7999999999999997e-01;
  a14=(a14*a1);
  a14=(a14*a9);
  a2=sin(a2);
  a10=(a10*a2);
  a14=(a14-a10);
  a0=(a0*a14);
  if (res[0]!=0) res[0][10]=a0;
  a0=1.0197838058331634e+00;
  a14=1.6700000000000001e-01;
  a14=(a14*a12);
  a12=-1.6700000000000001e-01;
  a12=(a12*a15);
  a14=(a14-a12);
  a12=-1.7499999999999999e-01;
  a12=(a12*a17);
  a14=(a14+a12);
  a12=1.7499999999999999e-01;
  a12=(a12*a11);
  a14=(a14+a12);
  a12=3.3000000000000002e-01;
  a12=(a12*a1);
  a12=(a12*a4);
  a14=(a14-a12);
  a0=(a0*a14);
  if (res[0]!=0) res[0][11]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void bluerov2_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int bluerov2_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real bluerov2_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* bluerov2_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* bluerov2_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int bluerov2_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
